[project]
name = "daily-briefs-microsoft-foundry-agentic-services"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-projects>=2.7.0",
    "azure-identity>=1.25.3",
    "fastapi>=0.141.1",
    "openai>=3.19.2",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.54.0",
]

[tool.basedpyright]
venvPath = "."
venv = ".venv"
